/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.util.HashMap;
import java.util.Map;

import main.httpclient.HttpsClient;
import main.httpclient.HttpsClientBuilder;

public class App {
    public static void main(String[] args) throws Exception {

        Map<String, String> headers = new HashMap<>();
        headers.put("Accept-Charset", "UTF-8");

        HttpsClient httpsClient
         = HttpsClientBuilder
            .create("https://www.naver.com")
            .setMethod("GET")
            .setHeader(headers)
            .setUseCaches(false)
            .build();


        System.out.println(httpsClient.getStatusCode());
        System.out.println(httpsClient.getResponseBody());

    }
}